# Generated by Django 4.1.7 on 2023-02-22 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.TextField(default='', max_length=200)),
                ('product_price', models.IntegerField(default=0)),
                ('product_img', models.ImageField(upload_to='products')),
                ('product_desc', models.TextField(default='', max_length=6000)),
            ],
        ),
    ]
