# Generated by Django 4.1.7 on 2023-02-22 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdata',
            name='product_cat',
            field=models.TextField(default='', max_length=100),
        ),
    ]
