# Generated by Django 4.1.7 on 2023-02-22 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mainpage', '0003_cartdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartdata',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
